spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/security
    username: myuser
    password: secret
  application:
    name: security
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 716274612608-8ujjm8cpctu02g88o62q3loni8jon6qt.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile



  jwt:
    jwtSecret: "verysecretkey-should-be-at-least-256-bits-long!"
    jwtExpirationMs: 10000000

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: /db/changelog/changelog.xml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
